name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Redeploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIV_KEY }}
          script: |
            cd ~/repos/joshua-payne.dev
            docker compose -f prod.docker-compose.yaml down
            git pull --rebase
            docker compose -f prod.docker-compose.yaml up --build --detach

      - name: Test Website Connection
        run: |
          sleep 5
          curl --output /dev/null --silent --location --fail http://joshua-payne.dev
